# Generated by Django 5.2.4 on 2025-07-12 07:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseAnnouncement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "website_course-announcement",
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAnnouncementCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("lector", models.CharField(max_length=255)),
                ("date", models.DateField(default=datetime.date.today)),
                ("description", models.TextField()),
                (
                    "course_announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="website.courseannouncement",
                    ),
                ),
            ],
            options={
                "db_table": "website_course-announcement-card",
            },
        ),
        migrations.CreateModel(
            name="DirectionCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "direction_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="website.direction",
                    ),
                ),
            ],
            options={
                "db_table": "website_direction-card",
            },
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_sections",
                        to="website.homepage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="direction",
            name="homepage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="website.homepage"
            ),
        ),
        migrations.AddField(
            model_name="courseannouncement",
            name="homepage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_announcements",
                to="website.homepage",
            ),
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_part1", models.CharField(max_length=255)),
                ("title_part2", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "homepage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissionCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "mission_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="website.mission",
                    ),
                ),
            ],
            options={
                "db_table": "website_mission-card",
            },
        ),
        migrations.CreateModel(
            name="MissionSubsection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "mission_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="website.mission",
                    ),
                ),
            ],
            options={
                "db_table": "website_mission-subsection",
            },
        ),
    ]
