# Generated by Django 5.2.4 on 2025-07-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DirectionSection",
            new_name="Direction",
        ),
        migrations.RenameModel(
            old_name="DirectionSectionCard",
            new_name="DirectionCard",
        ),
        migrations.RenameModel(
            old_name="HeroSection",
            new_name="Hero",
        ),
        migrations.RenameModel(
            old_name="MissionSection",
            new_name="Mission",
        ),
    ]
