# Generated by Django 5.2.4 on 2025-07-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directioncard",
            old_name="text",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="hero",
            old_name="title",
            new_name="title_part1",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="title_part1",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="title_part2",
        ),
        migrations.AddField(
            model_name="hero",
            name="title_part2",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hero",
            name="homepage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="website.homepage"
            ),
        ),
        migrations.AlterField(
            model_name="missionsubsection",
            name="mission_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_subsections",
                to="website.mission",
            ),
        ),
    ]
