# Generated by Django 5.2.4 on 2025-07-13 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_text_directioncard_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="missioncard",
            old_name="text",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="courseannouncementcard",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
