# Generated by Django 5.2.4 on 2025-07-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_directionsection_direction_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="courseannouncement",
            table="website_course-announcement",
        ),
        migrations.AlterModelTable(
            name="courseannouncementcard",
            table="website_course-announcement-card",
        ),
        migrations.AlterModelTable(
            name="directioncard",
            table="website_direction-card",
        ),
        migrations.AlterModelTable(
            name="missioncard",
            table="website_mission-card",
        ),
        migrations.AlterModelTable(
            name="missionsubsection",
            table="website_mission-subsection",
        ),
    ]
