# Generated by Django 5.2.4 on 2025-07-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_rename_text_missioncard_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseannouncement",
            options={
                "verbose_name": "6. CourseAnnouncement",
                "verbose_name_plural": "6. CourseAnnouncement",
            },
        ),
        migrations.AlterModelOptions(
            name="courseannouncementcard",
            options={
                "verbose_name": "7. CourseAnnouncementCard",
                "verbose_name_plural": "7. CourseAnnouncementCard",
            },
        ),
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "4. Direction",
                "verbose_name_plural": "4. Direction",
            },
        ),
        migrations.AlterModelOptions(
            name="directioncard",
            options={
                "verbose_name": "5. DirectionCard",
                "verbose_name_plural": "5. DirectionCard",
            },
        ),
        migrations.AlterModelOptions(
            name="mission",
            options={"verbose_name": "1. Mission", "verbose_name_plural": "1. Mission"},
        ),
        migrations.AlterModelOptions(
            name="missioncard",
            options={
                "verbose_name": "3. MissionCard",
                "verbose_name_plural": "3. MissionCard",
            },
        ),
        migrations.AlterModelOptions(
            name="missionsubsection",
            options={
                "verbose_name": "2. MissionSubsection",
                "verbose_name_plural": "2. MissionSubsection",
            },
        ),
    ]
