# Generated by Django 5.2.4 on 2025-07-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_courseannouncement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseannouncementcard",
            name="image",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
