# Generated by Django 5.2.4 on 2025-07-14 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_courseannouncementcard_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_detail",
                        to="website.courseannouncementcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseCurator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.CharField(max_length=255)),
                ("image", models.URLField()),
                ("description", models.TextField()),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curator",
                        to="website.coursedetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutCourse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_course",
                        to="website.coursedetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeroSectionCourse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("image", models.URLField()),
                ("section_title", models.CharField(max_length=255)),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_section",
                        to="website.coursedetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoCourse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField()),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_photo",
                        to="website.coursedetail",
                    ),
                ),
            ],
        ),
    ]
