# Generated by Django 5.2.4 on 2025-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_feedback_courseannouncementcard_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseannouncementcard",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
