# Generated by Django 5.2.4 on 2025-07-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_courseannouncementcard_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcourse",
            options={
                "verbose_name": "10. AboutCourse",
                "verbose_name_plural": "10. AboutCourse",
            },
        ),
        migrations.AlterModelOptions(
            name="coursecurator",
            options={
                "verbose_name": "9. CourseCurator",
                "verbose_name_plural": "9. CourseCurator",
            },
        ),
        migrations.AlterModelOptions(
            name="coursedetail",
            options={
                "verbose_name": "7. CourseDetail",
                "verbose_name_plural": "7. CourseDetail",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "12. Feedback",
                "verbose_name_plural": "12. Feedback",
            },
        ),
        migrations.AlterModelOptions(
            name="herosectioncourse",
            options={
                "verbose_name": "8. HeroSectionCourse",
                "verbose_name_plural": "8. HeroSectionCourse",
            },
        ),
        migrations.AlterModelOptions(
            name="photocourse",
            options={
                "verbose_name": "11. PhotoCourse",
                "verbose_name_plural": "11. PhotoCourse",
            },
        ),
        migrations.AlterModelTable(
            name="aboutcourse",
            table="website_about-course",
        ),
        migrations.AlterModelTable(
            name="coursecurator",
            table="website_course-curator",
        ),
        migrations.AlterModelTable(
            name="coursedetail",
            table="website_course-detail",
        ),
        migrations.AlterModelTable(
            name="feedback",
            table="website_feedback",
        ),
        migrations.AlterModelTable(
            name="herosectioncourse",
            table="website_course-hero-section-course",
        ),
        migrations.AlterModelTable(
            name="photocourse",
            table="website_photo-course",
        ),
    ]
