# Generated by Django 5.2.4 on 2025-07-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_aboutcourse_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcourse",
            options={
                "verbose_name": "12. AboutCourse",
                "verbose_name_plural": "12. AboutCourse",
            },
        ),
        migrations.AlterModelOptions(
            name="courseannouncementcard",
            options={
                "verbose_name": "8. CourseAnnouncementCard",
                "verbose_name_plural": "8. CourseAnnouncementCard",
            },
        ),
        migrations.AlterModelOptions(
            name="coursecurator",
            options={
                "verbose_name": "11. CourseCurator",
                "verbose_name_plural": "11. CourseCurator",
            },
        ),
        migrations.AlterModelOptions(
            name="coursedetail",
            options={
                "verbose_name": "9. CourseDetail",
                "verbose_name_plural": "9. CourseDetail",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "14. Feedback",
                "verbose_name_plural": "14. Feedback",
            },
        ),
        migrations.AlterModelOptions(
            name="herosectioncourse",
            options={
                "verbose_name": "10. HeroSectionCourse",
                "verbose_name_plural": "10. HeroSectionCourse",
            },
        ),
        migrations.AlterModelOptions(
            name="photocourse",
            options={
                "verbose_name": "13. PhotoCourse",
                "verbose_name_plural": "13. PhotoCourse",
            },
        ),
    ]
