# Generated by Django 5.2.4 on 2025-07-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_aboutcourse_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="course_id",
        ),
    ]
