# Generated by Django 5.2.4 on 2025-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_remove_feedback_course_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecurator",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
