# Generated by Django 5.2.4 on 2025-07-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_coursecurator_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursecurator",
            old_name="name",
            new_name="fullname",
        ),
    ]
