# Generated by Django 5.2.4 on 2025-07-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_name_coursecurator_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_section', to='website.team')),
            ],
            options={
                'verbose_name': '15. TeamHeroSection',
                'verbose_name_plural': '15. TeamHeroSection',
                'db_table': 'website_team-hero-section',
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='website.team')),
            ],
            options={
                'verbose_name': '16. TeamInfo',
                'verbose_name_plural': '16. TeamInfo',
                'db_table': 'website_team-info',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('fullname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='website.team')),
            ],
            options={
                'verbose_name': '17. TeamMemberCard',
                'verbose_name_plural': '17. TeamMemberCard',
                'db_table': 'website_team-member-card',
            },
        ),
    ]
